---
title: "mics4_td"
author: "Trude"
date: "28-4-2021"
output: github_document:
  toc: true
  toc_depth: 3
  number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Lao PDR: MICS Data - mics4






```{r options}

options(scipen = 999) # suppress scientific notion

```



```{r packages}

library(tidyverse)

# library(expss) # export

library(haven) 

library(sjPlot)

#library(sjlabelled)

#library(labelled)

#library(surveytoolbox) # install with #devtools::install_github("martinctc/surveytoolbox")

library(lubridate) # working with dates

library(survey)

#library(sjmisc)

#library(knitr)

library(janitor)

#library(survminer)

library(DataExplorer)

library(naniar)

```



## Data


```{r dataset mics4}

# package haven
mics4.ch <- read_sav("./data/mics4/ch.sav")

mics4.wm <- read_sav("./data/mics4/wm.sav")

```

### merging women to children and subset children under 3

```{r merging}
# selecting subset of variables of women's dataset
mics4.wm_var <- subset(mics4.wm, select = c("HH1", "HH2", "LN", "MN1", "MN2A", "MN2B", "MN2C", "MN2F", "MN2G", "MN2X", "MN3"))

# change variable name in women dataset in order to match with children's
mics4.wm_var$UF4 <- mics4.wm_var$LN
mics4.wm_var$UF4

# 11258 281
# 23937 12 


# Merge joining variables from dataset woman to dataset children_2017 using as key variable: UF4 (mothers or caretakers line number in ch.sav).
# Common variables used to merge are: HH1, HH2, UF4 in children, LN in women
mics4.ch2 <- merge(mics4.ch, mics4.wm_var, by=c("HH1", "HH2", "UF4"), all.x = TRUE)

mics4.ch %>% count(CAGE, IM14)

#subset children under 3
mics4.ch2 %>% filter(CAGE < 36) -> mics4.ch # 6591

```

```{r}

```

